services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8163235507:AAGWWz1guEqNBQdH6lHNRxGQXl4KyoHia4I"